## Name: Jugal Deshmukh
## Task-6 (Numpy)

In [1]:
#Question 1 (Arrays)

import numpy

def arrays(arr):
    
    ar1 = arr[::-1]
    n_array = numpy.array(ar1, float)
    return n_array


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#Question 2 (Shape and Reshape)

import numpy

l = list(map(int, input("Enter the list of integers:").split()))
ar = numpy.array(l)
#shape function of numpy converts an array of integers into a 3x3 matrix or numpy array
ar.shape=(3,3)
print(ar)

Enter the list of integers:1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
#Question 3 (Transpose and Flatten)

import numpy

n, m= list(map(int, input("Enter the M X N form:").split()))
l1=[]
for i in range(n):
    a = list(map(int, input("Enter the integers in the matrix:").split()))
    l1.append(a)
ar = numpy.array(l1)
#transpose function will transpose the list of integers 
print(numpy.transpose(ar))
#flatten function will convert the transposed array of integers into single dimension
print(ar.flatten())

Enter the M X N form:2 2
Enter the integers in the matrix:1 2
Enter the integers in the matrix:3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [2]:
#Question 4 (Concatenate)
import numpy as np

n,m,p = map(int, input().split())

l1=[]
l2=[]

for i in range(n):
    x=list(map(int,input().split()))
    l1.append(x)
    
for i in range(m):
    y=list(map(int,input().split()))
    l2.append(y)

arr1=np.array(l1)
arr2=np.array(l2)

print(np.concatenate((arr1,arr2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [3]:
#Question 5 (Zeros and Ones)
import numpy as np

numbers = list(map(int,input().split()))

print(np.zeros(numbers,dtype=np.int))
print(np.ones(numbers,dtype=np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [4]:
#Question 6 (Eye and Identity)

import numpy as np

n,m= map(int, input().split())

#this is to add spaces between the integers
np.set_printoptions(sign=" ")
print(np.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [5]:
#Question 7 (Array Mathematics)
import numpy as np

x, y = map(int, input().split())

X = np.array([list(map(int, input().split())) for _ in range(x)], int)
Y = np.array([list(map(int, input().split())) for _ in range(x)], int)

print(np.add(X,Y))
print(np.subtract(X,Y))
print(np.multiply(X,Y))
print(np.floor_divide(X,Y))
print(np.mod(X,Y))
print(np.power(X,Y))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [6]:
#Question 8 (Floor, Ceil and Rint)

import numpy as np

list1 = list(map(float,input().split()))
#this is to add spaces between the integers
np.set_printoptions(sign=" ")
arr=np.array(list1)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [7]:
#Question 9 (Sum and Prod)
import numpy as np

n,m= map(int, input().split())

l1=[]

for i in range(n):
    x=list(map(int,input().split()))
    l1.append(x)

arr=np.array(l1)
print(np.prod(np.sum(arr,axis=0),axis=0))

2 2
1 2
3 4
24


In [1]:
#Question 10 (Min and Max)
import numpy as np

n,m = map(int, input().split())

l1=[]

for i in range(n):
    x=list(map(int,input().split()))
    l1.append(x)

arr = np.array(l1)
print(np.max(np.min(arr,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


In [2]:
#Question 11 (Mean, Var and Std)

import numpy as np

n,m = map(int, input().split())

l1=[]

for i in range(n):
    x=list(map(int,input().split()))
    l1.append(x)

arr = np.array(l1)
np.set_printoptions(legacy='1.13')
print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(np.std(arr))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [10]:
#Question 12 (Dot and Cross)

import numpy as np

num = int(input())

x = np.array([input().split() for i in range(num)], dtype=int)

y = np.array([input().split() for i in range(num)], dtype=int)

print(x)
print(y)

print(x.dot(y))

2
1 2
3 4
1 2
3 4
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


In [11]:
#Question 13 (Inner and Outer)
import numpy as np

x = np.array(input().split(),int)
y = np.array(input().split(),int)

print(np.inner(x,y))
print(np.outer(x,y))

0 1
2 3
3
[[0 0]
 [2 3]]


In [12]:
#Question 14 (Polynomials)

import numpy as np

l1 = list(map(float,input().split()))

x = int(input())
arr = np.array(l1)
print(np.polyval(arr,x))

1.1 2 3
0
3.0


In [13]:
#Question 15 (Linear Algebra)

import numpy as np

n = int(input())

l1=[]

for i in range(n):
    x=list(map(float,input().split()))
    l1.append(x)
    
arr=np.array(l1)
r=np.linalg.det(arr)
print(round(r,2))

2
1.1 1.1
1.1 1.1
0.0
