## Name: Jugal Deshmukh
## Task - 8 (Statistics Questions)

In [1]:
import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity= 'all'

import math
import statistics
import numpy as np
import pandas as pd

# Question 1

Binomial Distribution I



The ratio of boys to girls for babies born in Russia is  1.09:1 . If there is 1 child born per birth, what proportion of Russian families with exactly 6 children will have at least 3 boys?   

Write a program to compute the answer using the above parameters. Then print your result, rounded to a scale of 3 decimal places (i.e.,1.234 format).  

Input Format   

A single line containing the following values:  

1.09 1  
If you do not wish to read this information from stdin, you can hard-code it into your program.

Output Format

Print a single line denoting the answer, rounded to a scale of 3 decimal places (i.e.,1.234 format).

[Day 4: Binomial Distribution I](https://www.hackerrank.com/challenges/s10-binomial-distribution-1/problem)



 $ P(x=i) = \frac {n!}{i!(n-i)!} p^i(1-p)^{n-i} $

In [2]:
def P_x(n,i,p):
    numerator = math.factorial(n)
    denominator = math.factorial(i)*math.factorial(n-i)
    nCi= numerator/denominator
    q =1-p
    P_x = nCi*(p**i)*(q**(n-i))
    return(P_x)

In [3]:
input_ = list(map(float,input().split()))
i =3 #success[3,4,5,6]
n = 6  # number of trails
girls_ratio = input_[1]

boys_ratio = input_[0]
p = boys_ratio/(girls_ratio+boys_ratio)

Output = 0
for j in range(i,n+1):
    Output += P_x(n,j,p) 
    
print(round(Output,ndigits=3))


1.10 1
0.7


## Question2
Binomial Distribution II

Objective
In this challenge, we go further with binomial distributions. We recommend reviewing the previous challenge's Tutorial before attempting this problem.

**Task**     
A manufacturer of metal pistons finds that, on average, **12%** of the pistons they manufacture are rejected because they are incorrectly sized. What is the probability that a batch of  pistons will contain:

No more than **2** rejects?  
At least **2** rejects?

**Input Format**     

A single line containing the following values (denoting the respective percentage of defective pistons and the size of the current batch of pistons):

12 10  
If you do not wish to read this information from stdin, you can hard-code it into your program.

**_Output Format_**  

Print the answer to each question on its own line:    

The first line should contain the probability that a batch of **10** pistons will contain no more than **_2_** rejects.   
The second line should contain the probability that a batch of **10** pistons will contain at least **2** rejects.   
Round both of your answers to a scale of **3** decimal places (i.e.,**1.234**  format).   





[Binomial Distribution II](https://www.hackerrank.com/challenges/s10-binomial-distribution-2/problem)



 $$ P(x=i) = \frac {n!}{i!(n-i)!} p^i(1-p)^{n-i} $$

In [4]:
b =list(map(int,input().split()))
n=b[1]
p =b[0]/100
reject=0
i=2
for i in range(i+1):
    reject += P_x(n,i,p)
print(round(reject,3))
j= 2
reject_2 = 0
for i in range(2,10):
    reject_2 += P_x(n,i,p)
print(round(reject_2,3))
    


12 10
0.891
0.342


## Question 3
Normal Distribution I

In a certain plant, the time taken to assemble a car is a random variable, , having a normal distribution with a mean of **20** hours and a standard deviation of **2** hours. What is the probability that a car can be assembled at this plant in:

1. Less than **19.5** hours?   
2. Between **20** and **22** hours?   

Input Format

There are **3** lines of input (shown below):

20 2
19.5
20 22
The first line contains **2** space-separated values denoting the respective mean and standard deviation for **X**. The second line contains the number associated with question **1**. The third line contains **2** space-separated values describing the respective lower and upper range boundaries for question **2**.

If you do not wish to read this information from stdin, you can hard-code it into your program.

Output Format

There are two lines of output. Your answers must be rounded to a scale of **3** decimal places (i.e.,**1.234** format):

1. On the first line, print the answer to question **1** (i.e., the probability that a car can be assembled in less than **19.5** hours).     
2. On the second line, print the answer to question **2** (i.e., the probability that a car can be assembled in between **20** to **22** hours).  


[Normal Distribution I](https://www.hackerrank.com/challenges/s10-normal-distribution-1/problem)



In [5]:
from scipy.stats import norm
import numpy as np


In [6]:
def Z_score(mean,std, observation):
    z= (observation-mean)/std
    return(z)

In [7]:
#given 
mean =20
std = 2

In [8]:
#Less than **19.5** hours?   
observation= 19.5
z = Z_score(mean,std,observation)
p_value = 1.0 - norm.cdf(np.abs(z))
print(round(p_value,3))


0.401


In [9]:
#Between **20** and **22** hours?
observation1 = 20
z_20 = Z_score(mean,std,observation1)

p_20 = norm.cdf(np.abs(z_20))
print(p_20)
observation2= 22
z_22 = Z_score(mean,std, observation2)
p_22 = norm.cdf(np.abs(z_22))
print(p_22)

#we need middel portion so 

print("Between **20** and **22** hours is ",round((p_22-p_20),3))

0.5
0.8413447460685429
Between **20** and **22** hours is  0.341


## Question 4
Normal Distribution II

Objective
In this challenge, we go further with normal distributions. We recommend reviewing the previous challenge's Tutorial before attempting this problem.

Task
The final grades for a Physics exam taken by a large group of students have a mean of $ \mu=70 $ and a standard deviation of $ \sigma = 10 $ . If we can approximate the distribution of these grades by a normal distribution, what percentage of the students:

1. Scored higher than **80** (i.e., have a **grade>80**)?   
2. Passed the test (i.e., have a $grade\underline>60$)?
3. Failed the test (i.e., have a **grade<60**)?
Find and print the answer to each question on a new line, rounded to a scale of **2** decimal places.

Input Format

There are **3** lines of input (shown below):

70 10
80
60
The first line contains **2** space-separated values denoting the respective mean and standard deviation for the exam. The second line contains the number associated with question **1**. The third line contains the pass/fail threshold number associated with questions **2** and **3**.

If you do not wish to read this information from stdin, you can hard-code it into your program.

Output Format

There are three lines of output. Your answers must be rounded to a scale of  **2** decimal places (i.e.,**1.234**  format):

On the first line, print the answer to question **1** (i.e., the percentage of students having  **grade>80**).  
On the second line, print the answer to question **2** (i.e., the percentage of students having $grade\underline>60$).  
On the third line, print the answer to question  **3** (i.e., the percentage of students having **grade<60**).  


[Normal Distribution II](https://www.hackerrank.com/challenges/s10-normal-distribution-2/problem)


In [10]:
mean = 70
std = 10

In [12]:
mean, std  = map(int,input().split())

70 10


In [13]:
std

10

In [14]:
#(p>80)
observation = 80
z = Z_score(mean,std,observation)
print(z)
p_value = norm.cdf(np.abs(z))
print(round((1-p_value)*100,2))

1.0
15.87


In [15]:
#(p>=60)
observation1 = 60
z = Z_score(mean,std,observation1)

p_value = norm.cdf(np.abs(z))
print(round((p_value*100),2))
#p<60
print(round((1-p_value)*100,2))

84.13
15.87


## Question 5
The Central Limit Theorem I


A large elevator can transport a maximum of **9800** pounds. Suppose a load of cargo containing **49** boxes must be transported via the elevator. The box weight of this type of cargo follows a distribution with a mean of $\mu=205 $ pounds and a standard deviation of $\sigma =15 $ pounds. Based on this information, what is the probability that all **49** boxes can be safely loaded into the freight elevator and transported?

Input Format

There are **4** lines of input (shown below):

9800
49
205
15
The first line contains the maximum weight the elevator can transport. The second line contains the number of boxes in the cargo. The third line contains the mean weight of a cargo box, and the fourth line contains its standard deviation.

If you do not wish to read this information from stdin, you can hard-code it into your program.

Output Format

Print the probability that the elevator can successfully transport all **49** boxes, rounded to a scale of **4** decimal places (i.e., **1.234** format).

[The Central Limit Theorem I](https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-1/problem)

In [ ]:
from scipy.stats import norm
import numpy as np

In [16]:
x= 9800
n= 49
mean = 205
sigma =15
random_variable = x/n

In [17]:
random_variable

200.0

In [18]:
import math

In [19]:
def Z_score(mean,std, observation,n):
    z= (observation-mean)/(std/math.sqrt(n))
    return(z)

In [20]:
Z_score = Z_score(mean,sigma,random_variable,n)

In [21]:
Z_score

-2.3333333333333335

In [22]:
from scipy.stats import norm
import numpy as np
p_value = 1.0 - norm.cdf(np.abs(Z_score))

print(round(p_value,4))

0.0098


## Question 6

The Central Limit Theorem II

The number of tickets purchased by each student for the University X vs. University Y football game follows a distribution that has a mean of $\mu = 2.4 $ and a standard deviation of $\sigma = 2.0 $.

A few hours before the game starts, **100** eager students line up to purchase last-minute tickets. If there are only **250** tickets left, what is the probability that all **100** students will be able to purchase tickets?

Input Format

There are **4** lines of input (shown below):

250
100
2.4
2.0
The first line contains the number of last-minute tickets available at the box office. The second line contains the number of students waiting to buy tickets. The third line contains the mean number of purchased tickets, and the fourth line contains the standard deviation.

If you do not wish to read this information from stdin, you can hard-code it into your program.

Output Format

Print the probability that **100** students can successfully purchase the remaining **250** tickets, rounded to a scale of  **4**decimal places (i.e.,**1.234**  format).

[The Central Limit Theorem II](https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-2/problem)

In [23]:
mean= 2.4
std = 2.0
n = 100
number_of_tickets =250 

observation = number_of_tickets/n

In [24]:
numerator = observation-mean

In [25]:
numerator

0.10000000000000009

In [26]:
def z_score(mean, std,observation,n):
    numarator = observation-mean
    denominator = std/math.sqrt(n)
    z = numarator/denominator
    return(z)

In [27]:
z = z_score(mean, std,observation,n)

In [28]:
print(z)

0.5000000000000004


In [29]:
pvalue = norm.cdf(np.abs(z))

In [30]:
print(round(pvalue,4))

0.6915


## Question 7

The Central Limit Theorem III


You have a sample of **100**  values from a population with mean $\mu = 500$ and with standard deviation $\sigma= 80$. Compute the interval that covers the middle **95** of the distribution of the sample mean; in other words, compute **A** and **B** such that **(P<x<B)=0.95** . Use the value of **Z=1.96** . Note that  is the z-score.

**Input Format**

There are five lines of input (shown below):

100  
500   
80   
.95   
1.96   
The first line contains the sample size. The second and third lines contain the respective mean ($\mu$) and standard deviation ($\sigma$). The fourth line contains the distribution percentage we want to cover (as a decimal), and the fifth line contains the value of **Z**.

If you do not wish to read this information from stdin, you can hard-code it into your program.

**Output Format**

Print the following two lines of output, rounded to a scale of **2** decimal places (i.e.,**1.234** format):

1. On the first line, print the value of **A**.
2. On the second line, print the value of **B**.

[The Central Limit Theorem III](https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-3/problem)


In [31]:
# the central limit therom fallows the normal distribition 95% of the data fallows in 2stds from the mean
#from CLT smaples_mean = population mean
#s = sigma/sqrt(n)
mu= 500
sigma= 80
n =100
s = sigma/math.sqrt(n)

a = mu-(2*s)
b = mu+(2*s)

print(a,b,sep='\n')

484.0
516.0


## Question 8

Pearson Correlation Coefficient I



[Pearson Correlation Coefficient I](https://www.hackerrank.com/challenges/s10-pearson-correlation-coefficient/problem)

In [35]:
n = int(input())
x= np.array(input().split(),np.float)
y= np.array(input().split(),np.float)

a =np.corrcoef(x,y)
print(([0,1],3))
print(a)

10
10 9.8 8 7.8 7.7 7 6 5 4 2 
200 44 32 24 22 17 15 12 8 4
([0, 1], 3)
[[1.         0.61247219]
 [0.61247219 1.        ]]


In [36]:
import pandas as pd
n = int(input())
x= np.array(input().split(),np.float)
y= np.array(input().split(),np.float)

df = pd.DataFrame()
df['x'] =x
df['y']=y

a =np.corrcoef(x,y)
print(round(df.corr(),3))

10
10 9.8 8 7.8 7.7 7 6 5 4 2
200 44 32 24 22 17 15 12 8 4
       x      y
x  1.000  0.612
y  0.612  1.000


## Question 9

Least Square Regression Line


A group of five students enrolls in Statistics immediately after taking a Math aptitude test. Each student's Math aptitude test score,**x**, and Statistics course grade,**y** , can be expressed as the following list of **(x,y)**  points:

1. (95,85)   
2. (85,95)   
3. (80,70)   
4. (70,65)   
5. (60,70)   


If a student scored an **80** on the Math aptitude test, what grade would we expect them to achieve in Statistics? Determine the equation of the best-fit line using the least squares method, then compute and print the value of **y** when **x=80**.

**Input Format**

There are five lines of input; each line contains two space-separated integers describing a student's respective **x** and **y** grades:

95 85   
85 95   
80 70   
70 65  
60 70   
If you do not wish to read this information from stdin, you can hard-code it into your program.

**Output Format**

Print a single line denoting the answer, rounded to a scale of **3** decimal places (i.e.,**1.234**  format).

[Least Square Regression Line](https://www.hackerrank.com/challenges/s10-least-square-regression-line/problem)


In [42]:
from sklearn.linear_model import LinearRegression

In [37]:
input_ = [list(map(int,input().split())) for i in range(5)]


95 85
85 95
80 70
70 65
60 70


In [38]:
input_

[[95, 85], [85, 95], [80, 70], [70, 65], [60, 70]]

In [39]:
x = np.array([input_[i][0] for i in range(len(input_))]).reshape(-1,1)
y = np.array([input_[i][1] for i in range(len(input_))])


In [40]:
print(x,y,sep = '\n')

[[95]
 [85]
 [80]
 [70]
 [60]]
[85 95 70 65 70]


In [43]:
model = LinearRegression()

In [44]:
model.fit(x,y)

LinearRegression()

In [45]:
model.intercept_

26.780821917808225

In [46]:
model.coef_

array([0.64383562])

In [47]:
y_pred80 = model.predict(np.array(80).reshape(-1,1))

In [48]:
print(np.round(y_pred80,3)[0])

78.288


# Question 10

[Multiple Linear Regression](https://www.hackerrank.com/challenges/s10-multiple-linear-regression/problem)



In [49]:
m,n = list(map(int,input().split()))
x_1 = []
x_2 = []
y = []
input_ = [list(map(float,input().split())) for i in range(n)]
x_1 = np.array([input_[i][0] for i in range(len(input_))])
x_2 = np.array([input_[i][1] for i in range(len(input_))])
y = np.array([input_[i][2] for i in range(len(input_))])

2 7
0.18 0.89 109.85
1.0 0.26 155.72
0.92 0.11 137.66
0.07 0.37 76.17
0.85 0.16 139.75
0.99 0.41 162.6
0.87 0.47 151.77


In [50]:
df = pd.DataFrame()
df['x_1'] =x_1
df['x_2'] =x_2
df['y'] =y

In [51]:
df.head()

x_1   x_2       y
0  0.18  0.89  109.85
1  1.00  0.26  155.72
2  0.92  0.11  137.66
3  0.07  0.37   76.17
4  0.85  0.16  139.75

In [52]:
x = df.drop(['y'],axis=1)
y = df['y']

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
model = LinearRegression()

In [55]:
model.fit(x,y)

LinearRegression()

In [56]:
model.coef_,model.intercept_

(array([90.69331739, 46.46296549]), 52.411499045060836)

## testing

In [57]:
q = int(input())
test = [list(map(float,input().split())) for i in range(q)]
x_1_test = np.array([test[i][0] for i in range(len(test))])
x_2_test = np.array([test[i][1] for i in range(len(test))])

4
0.49 0.18
0.57 0.83
0.98 0.13
0.76 0.18


In [58]:
x_1_test

array([0.49, 0.57, 0.98, 0.76])

In [59]:
df1 = pd.DataFrame()

df1['x_1_test'] = x_1_test
df1['x_2_test']  = x_2_test

In [60]:
df1

x_1_test  x_2_test
0      0.49      0.18
1      0.57      0.83
2      0.98      0.13
3      0.76      0.18

In [61]:
model.predict(df1)

array([105.21455835, 142.67095131, 147.3311356 , 129.70175405])